# Generated by Django 4.0.4 on 2022-05-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuessCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quetion', models.CharField(max_length=100)),
                ('op1', models.IntegerField()),
                ('op2', models.IntegerField()),
                ('op3', models.IntegerField()),
                ('op4', models.IntegerField()),
                ('op5', models.IntegerField()),
            ],
        ),
    ]
