# Generated by Django 4.0.4 on 2022-05-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guesscareer',
            old_name='quetion',
            new_name='question',
        ),
    ]
