# Generated by Django 4.0.4 on 2022-05-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_rename_quetion_guesscareer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guesscareer',
            old_name='op1',
            new_name='Option1',
        ),
        migrations.RenameField(
            model_name='guesscareer',
            old_name='op2',
            new_name='Option2',
        ),
        migrations.RenameField(
            model_name='guesscareer',
            old_name='op3',
            new_name='Option3',
        ),
        migrations.RenameField(
            model_name='guesscareer',
            old_name='op4',
            new_name='Option4',
        ),
        migrations.RenameField(
            model_name='guesscareer',
            old_name='op5',
            new_name='Option5',
        ),
        migrations.RenameField(
            model_name='guesscareer',
            old_name='question',
            new_name='Question',
        ),
    ]
